### ISSUE TITLE
When saving newly created draft with uploaded files, the metadata is saved, but the files arent

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1060]
Tested on RepOD:

![image](https://user-images.githubusercontent.com/8678301/83038523-581d8400-a03d-11ea-9cdc-dc52bdb3baae.png)

**Comment by wfenrich** [comment]
Im also unable to add files to an existing draft: 

![image](https://user-images.githubusercontent.com/8678301/83039124-0a554b80-a03e-11ea-96f9-22c328bb62c3.png)

**Comment by madryk** [comment]
Error resolved in different task #1041
