### ISSUE TITLE
After granting/declining access to a restricted file, the file access management page does not refresh

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1092]
Thus, a user may not be sure if the access has been successfully granted/declined. 

If I grant the access, a user is added to the list of users having access to the file, but his/her request is still visible - I have to manually refresh the page to clear it up. 

If I refuse the access, nothing happens - the request is not cleared until the page is refreshed.

**Comment by wfenrich** [comment]
This is how it looks like a second after I declined access to the file: 

![image](https://user-images.githubusercontent.com/8678301/83733411-c968c280-a64d-11ea-8430-e9f5738f75a1.png)

**Comment by tomaszblazejczyk** [comment]
Primefaces bug - cannot update datatable from an action inside it.
