### ISSUE TITLE
OAI_ORE Exporter exports only one author

### ISSUE THREAD

**Issue by dbojanek** [CeON/fairchive#1168]

**Comment by wfenrich** [comment]
Example from RepOD: 
https://repod.icm.edu.pl/api/datasets/export?exporter=OAIORE&persistentId=doi%3A10.18150/XMEUNL

It should look more like in Harvard: 
https://dataverse.harvard.edu/api/datasets/export?exporter=OAI_ORE&persistentId=doi%3A10.7910/DVN/5NKX4F
