### ISSUE TITLE
Add step excluding from XDS analysis datasets with multiple "Data Collection" metadata group

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1171]
It should be the first step of the whole workflow. 

Some older datasets may have multiple passings, which require special kind of analysis with XDS - quite diffrent from what we do. These datasets will have multiple groups of dataCollection metadata. 

If in the version there is more than one group of dataCollection metadata fields, do not perform XDS analysis.

User should be notified, that the analysis failed, but the step should also send a message. 

In the future we will use this message to make separate information on UI for failure at this specific step (as the case is quite distinct from "usual fails", such as errors - here we deliberately break the analysis).

**Comment by madryk** [comment]
This is already done
