### ISSUE TITLE
Display results of automatic analysis with XDS

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1172]
We should add a new “Automatic analysis” tab. 

The tab should be always visible (just as “Guestbook” tab is always visible even if there is no guestbook to show). 

What the tab should contain? It depends: 

If we are in the Draft version

`print(The attempt of automatic analysis with XDS will start after this version of this dataset is published.)`

else if (the dataset is under embargo) AND (the user has no permission allowing to view “Files” tab)

`print(Results of the automatic analysis with XDS of this version of the dataset will be available after the end of the embargo period, i.e. from <endOfTheEmbargoDate>.)`

else if [ (the dataset is NOT under embargo) OR (the dataset is under embargo AND the user has permissions allowing to view “Files” tab) ] AND (the analysis is in progress)

`print(Automatic analysis with XDS of this version of the dataset is in progress.)`

else if [ (the dataset is NOT under embargo) OR (the dataset is under embargo AND the user has permissions allowing to view "Files" tab) ] AND (the analysis was not performed)

`print(Automatic analysis with XDS of this version of the dataset was not performed.)`

else if  [ (the dataset is NOT under embargo) OR (the dataset is under embargo AND the user has permissions allowing to view "Files" tab) ] AND (the analysis succeded)

`<success screen>`

else if [ (the dataset is not under embargo) OR (the dataset is under embargo AND the user has permission allowing to view "Files" tab) ] AND (the analysis failed) 

`<failure screen>`

**Comment by tomaszblazejczyk** [comment]
https://docs.google.com/document/d/1FqVCrfgYMGVdkFbbmGHJEND_xfq6UrQ_lm_JM99sgSM/edit
