### ISSUE TITLE
Can't add new dataverse

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1176]
Probably a bug related to banner fix: 

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at <email> to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
Apache/2.4.29 (Ubuntu) Server at <host> Port 443

**Comment by madryk** [comment]
Duplicate of #1155
