### ISSUE TITLE
N/A metadata value should work in a more reasonable manner

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1250]
Currently it is possible for all users to use the "N/A" trick and bypass the metadata requirements. But the metadata requirements have some purpose and it should not be that easy to blow them off. 

We should leave this possibility only for special occasions and for a special breed of people: the mighty superusers. 

So only a superuser should be able to create or save a dataset having a field (any field) with N/A as a value. 

This solution seems obvious for non-text fields, but why we should disable the possibility of N/A value for text and textbox fields?

Well, the point is that N/A not only bypasses the validation, but also disables the visibility of a given field. So it still has a special use when it comes to text values; a use that should be reserved for a superuser.

**Comment by MrK191** [comment]
What should we do about imported dataset with missing Controlled Vocabulary Values?
ATM if we would remove "N/A" in dataset fields I'm not sure if we would be compatible with OAI_OREE exporter.

Work notes:

> Dataset#validateLenient
> 
> kiedy N/A dziala, konsekwencje ze mamy w bazie, walidacja gdy wylaczymy co sie stanie
> 
> Guestbook Response Download - Date jeśli nie ma to daj N/A i findArrayByGuestbookIdAndDataverseId do wyswietlania na stronie
> DatasetVersionDifference - N/A jeśli nie ma wartości.
> Konfiguracja HavevestClient - jesli null to zamanka na N/A - uzywane do jsona aby pokazac ustawienia
> Naprawa contraint violation - datasetfieldy
> indexowanie - vocab dataverseSubject != N/A index
> loadNAControlledVocabularyValue - if empty create and save ControlledVocabularyValue to DB otherwise nothing
> DSF - getValuesWithoutNaValues (appears to be only used for sending info to solr; changed to return values
>      * instead of display values)
> SWORD - dodaja N/A do slownika jesli go nie ma
> SLOWNIK - jesli da sie nulla to popsuje mase rzeczy
> 
> 
> KATEGORIA ZMIANA NA null/""
> DSF Validator - NA na "" bez problemu bo i tak jest sprawdzane
> DSF - getFiedlDisplayValue
> generalnie dsf i dsf validator beda dzialaly tak samo - ale wyciaganie getValues ma !getFieldValue().isEmpty()
> 
> slowniki - constraint not null na value wiec nie mozna tak zamienic
