### ISSUE TITLE
XDS analysis fails if images in zip files are archived in a directory

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1258]
Example on test: https://doi.org/10.18150/FK2/BHVF73 – versions with images zipped with directory fail immediately, but the version with "flat" zip is analysed successfully. 

Probably adding -j to unzip command will do the job.

**Comment by wfenrich** [comment]
@tomaszblazejczyk can we close it? Probably was done elsewhere in mxrdr repo.

**Comment by tomaszblazejczyk** [comment]
https://github.com/CeON/mxrdr-extension/pull/44
