### ISSUE TITLE
Fix mess on "Edit license" modal window

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1290]
![image](https://user-images.githubusercontent.com/8678301/124911936-a09fc300-dfed-11eb-99fc-2fc15abe7315.png)

* Add title "Edit license/Edytuj licencję"
* What's the misterious small focus in the upper left corner?
* Make the modal window wider. 
* URL should be a simple input field, not a textarea. 
* Fix label on "Select file" button.
* Can't save even if the data I've provided seems to be correct. 
* At the very top we should inform users that "Asterisks indicate required fields". 
* License URL should be validated for being a required field and for being a valid URL.
* "Close" label on button actually should say "Cancel". 
* Badge should be validated for format (PNG, JPG/JPEG), file size (100 kbytes) and max. picture size (140x50). 
* Component for file upload should have an extra information regarding the size and format of the badge, placed above (just like it is on adding banner page). 
* If there are values, both URL and badge should be pre-filled.

**Comment by wfenrich** [comment]
Supported image types are JPG, or PNG and should be no larger than 100 KB. The maximum size for an image file is 140 pixels wide by 50 pixels high.

Wspierane typy plików to JPG oraz PNG, a ich rozmiar nie powinien przekraczać 100 KB. Maksymalne wymiary pliku graficznego to 140 x 50 pikseli (szerokość x wysokość).

**Comment by dbojanek** [comment]
- [x] - Add title "Edit license/Edytuj licencję"
- [x] - What's the misterious small focus in the upper left corner?
- [x] - Make the modal window wider.
- [x] - URL should be a simple input field, not a textarea.
- [x] - Fix label on "Select file" button.
- [x] - Can't save even if the data I've provided seems to be correct.
- [x] - At the very top we should inform users that "Asterisks indicate required fields".
- [x] - License URL should be validated for being a required field and for being a valid URL.
- [x] - "Close" label on button actually should say "Cancel".
- [x] - Badge should be validated for format (PNG, JPG/JPEG), file size (100 kbytes) and max. picture size (140x50).
- [x] - Component for file upload should have an extra information regarding the size and format of the badge, placed above (just like it is on adding banner page).
- [x] - If there are values, both URL and badge should be pre-filled.
