### ISSUE TITLE
A superuser should able to rerun automatic analysis via API

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1326]
For now, reanalysis via API should be enough – we will not perform this operation frequently. 

Possible scenarios: 

1. There is a new version of XDS, which fixes a major bug – we should make wholesale reanalysis, as all previous analyses became dubious. 
2. We've extended our analyses and now we are able to analyse dataset versions where the analysis was not performed. 
3. We've made a fix on our side and we believe that some analyses that previously failed, this time won't.
4. A superuser curated metadata in a way that may change the results of the previous analysis. 

Requirements: 

1. Rerun should be possible for superuser only, so we should identify him/her by a token. 
2. It should be possible to declare what should be analysed:
2.1. All latest published versions of all datasets for which the analysis was not performed.  
2.2. All latest published versions of all datasets for which the analysis failed. 
2.3. Specific version of a specific datasets. 

As a result, selected dataset versions should be queued for the reanalysis.

**Comment by tomaszblazejczyk** [comment]
How it works:
curl --location --request POST 'http://localhost:8080/api/admin/workflows/rerun?type=notPerformedOnly&key={API_KEY}'
curl --location --request POST 'http://localhost:8080/api/admin/workflows/rerun?type=failedOnly&key={API_KEY}'
curl --location --request POST 'http://localhost:8080/api/admin/workflows/{DATASET_ID}/rerun?version={SPECIFIC_VERSION}&key={API_KEY}'
