### ISSUE TITLE
Check the insides of the aws-sdk-java to establish how the transfer of files smaller than the maximum size of a single chunk is really made

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1347]
Currently on the Dataverse side we treat both types of files in the Dataverse in the same manner: we ask for multipart upload. 

But we are not sure what happens or may happen on a lower level: 

1) are files smaller than chunk_size uploaded as single-chunk multiparts, or maybe in these cases they are put as a simple objects, not as multiparts?
2) is it possible to compare a specific md5 stored in the Dataverse with md5 calculated on s3 side, similarly to what happens here: https://aws.amazon.com/premiumsupport/knowledge-center/data-integrity-s3/ ? Are there any differences regarding files smaller and larger than chunk_size?

**Comment by tomaszblazejczyk** [comment]
1. After lot of debugging work I can confirm that files smaller than multipart threshold are uploaded as single object - not marked for multipart upload. There is property in UploadMonitor named "multipartUploadId" which is null when uploading small files. By the way value of "multipartUploadId" is stored in s3 side and can be used to verify all parts in future improvements of integrity check engine.
2. Some tests proved that for non-multipart-uploaded files MD5 calculated by dataverse is identical with ETag obtained from s3 object metadata so it could be good comparison.
