### ISSUE TITLE
Can't publish datasets on repod test

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1360]
Błąd – Command edu.harvard.iq.dataverse.engine.command.impl.FinalizeDatasetPublicationCommand@4e0adfe failed: nullJeśli sądzisz, że jest to błąd, skontaktuj się z RepOD Pomoc w celu uzyskania pomocy.

**Comment by wfenrich** [comment]
On mxrdr test installation everything works fine, so it seems that it is something repod-specific.

**Comment by madryk** [comment]
There was a problem with datacite test account configuration
