### ISSUE TITLE
As a superuser I would like to be able to set up a user group based on domains of confirmed e-mails to make easy and cheap distinction between those users that should be allowed to make a deposit in a given institutional collection and those that should not

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1379]
Basically we would like to replicate what Harvard did here: https://guides.dataverse.org/en/latest/admin/mail-groups.html

In the first run we can make exact matches only and add regex support later.

**Comment by madryk** [comment]
Was done in:
https://github.com/CeON/dataverse/issues/1381

https://github.com/CeON/dataverse/issues/1382

https://github.com/CeON/dataverse/issues/1380
