### ISSUE TITLE
After change licence on one file all descriptions on all files are reseted

### ISSUE THREAD

**Issue by ghost** [CeON/fairchive#1459]
![image](https://user-images.githubusercontent.com/26048925/109777032-8ef37c80-7c03-11eb-9576-60ef5f82ef6d.png)

![image](https://user-images.githubusercontent.com/26048925/109777087-9d419880-7c03-11eb-9e7c-f23b4926898b.png)

**Comment by wfenrich** [comment]
Confirmed. A nasty, nasty bug, that may result in loosing a lot of work.
