### ISSUE TITLE
No info message after send reset password email

### ISSUE THREAD

**Issue by ghost** [CeON/fairchive#1462]
![image](https://user-images.githubusercontent.com/26048925/109812295-2f5d9700-7c2c-11eb-93f6-5440495c56f5.png)

**Comment by wfenrich** [comment]
If this email is associated with an account, then an email will be sent with further instructions to... 
Jeśli ten e-mail jest powiązany z kontem, wyślemy wiadomość z dalszymi instrukcjami na adres...
