### ISSUE TITLE
Issue when cite dataset - select BibTeX

### ISSUE THREAD

**Issue by ghost** [CeON/fairchive#1490]
![image](https://user-images.githubusercontent.com/26048925/110787699-f8ac0000-826d-11eb-93bc-273df7e2edae.png)

**Comment by wfenrich** [comment]
Seems like a bug. If it is not a JSON, we should not suggest it is.

**Comment by wfenrich** [comment]
For some reason, Firefox thinks it's JSON. It's not. Already solved on Harvard version.

**Comment by dbojanek** [comment]
I've copied Harvard solution for this issue - changing content type to text rather that json.
