### ISSUE TITLE
Some actions on dataset page ends with ISE

### ISSUE THREAD

**Issue by ghost** [CeON/fairchive#1580]
1. User creates dataset with file  (e.g. minimum metadata set and  one jpg file)
3. Saves dataset 
2. Sends for review
3. Logs out
4. Error after click on log out button

**Comment by ghost** [comment]
rds

1. User download all files in dataset 
2. Log out 
3. Error after click on log out button

**Comment by ghost** [comment]
1. User is on files list on dataset (dataset has more than 10 files)
2. Click on select all files button
3. Changes language
4. ISE error occurs

After click on Clear selection button - there is same problem - ISE

**Comment by ghost** [comment]
1. User is on files list
2. Some files are restricted
3. User checks all files and requests access
4. Changes language
5.  ISE error ocurrs

**Comment by MrK191** [comment]
https://github.com/IQSS/dataverse/issues/1393

**Comment by MrK191** [comment]
https://stackoverflow.com/questions/8026082/jsf-2-0-why-my-viewscope-beans-is-re-created-even-though-still-on-same-view
