### ISSUE TITLE
Issue with download files with diacritic marks

### ISSUE THREAD

**Issue by ghost** [CeON/fairchive#1581]
1. Files contain diacritic marks.
2. Download file - some diacritic marks are missing or changed.

Same issue on dataverse name with diacritic marks - when responses in guestbook are downloaded

**Comment by wfenrich** [comment]
Confirmed, I get a mess instead of "zażółć gęślą jaźń.txt"

**Comment by madryk** [comment]
Probably issue is with "Content-Disposition" response header.
