### ISSUE TITLE
After remove version sent to review - contributor cannot create new one

### ISSUE THREAD

**Issue by ghost** [CeON/fairchive#1584]
1. User create new version dataset and send to review
2. Reviewer remove this version 
3. Info message still is displayed:   Submitted for Review – The draft version of this dataset is currently under review prior to publication. 
4. User cannot create new version - edit button are unavailable and see messege "  Submitted for Review – The draft version of this dataset is currently under review prior to publication.

**Comment by wfenrich** [comment]
Confirmed. Deleting unpublished version by the admin does not unlock the dataset.

**Comment by wfenrich** [comment]
From the Admin perspective, the dataset still has a banner saying that it is being verified.
