### ISSUE TITLE
It should be possible to enforce e-mail confirmation

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1638]
Normal logging in, but without some features:
* It should be possible to turn this confirmation requirement on and off. 
* A logged in user  with unconfirmed e-mail sees on GUI a permanent, eyes-catching information that s/he should confirm his/her e-mail.
* Logged in user with unconfirmed e-mail sees no "Edit" or "Link" buttons on any DATAVERSE page, even on those where s/he has sufficient permissions. Also s/he cannot perform operations available under these buttons. Basically the page looks like for a user that is not logged in.
* Logged in user with unconfirmed e-mail sees no "Edit", "Edit Files", "Add + Edit Metadata", "Upload Files" or "Link" buttons on any FILE page, even on those where s/he has sufficient permissions. Also s/he cannot perform operations available under these buttons. Basically the page looks like for a user that is not logged in.
* Logged in user with unconfirmed e-mail sees no "Edit", "Edit Files", "Upload Files" or "Link" buttons on any DATASET, even on those where s/he has sufficient permissions. Also s/he cannot perform operations available under these buttons. Basically the page looks like for a user that is not logged in.
* When logged in user with unconfirmed e-mail clicks on "Request Access" to file button, s/he sees a modal window informing that e-mail confirmation is required to perform this operation.
* For API operations requiring token, we may consider changing generic message to include information about e-mail confirmation requirement. 
* Users with unconfirmed e-mail can be added to groups, but cannot perform operations resulting from such membership (as these are based on roles).
* We should be careful with some API endpoints, for instance listing content of a given dataverse.
* TBA whether user may perform operations resulting from "view unpublished dataset", "view Unpublished Dataverse" and "download restricted file" permissions.

**Comment by madryk** [comment]
We should modify methods in `PermissionServiceBean`:
`public Set<Permission> permissionsFor(DataverseRequest req, DvObject dvo) {`,
`private boolean hasPermissionsFor(DataverseRequest req, DvObject dvo, Set<Permission> required) {`
`private boolean hasPermissionsFor(RoleAssignee ra, DvObject dvo, Set<Permission> required) {`
we should also check (maybe it wouldn't be neccassary to change):
`private List<DvObject> whichChildrenHasPermissionsFor(DataverseRequest req, DvObjectContainer dvo, Set<Permission> required, boolean includeReleased) {`
When we will do that then we will be in situation when all operations in the app are secure. And all "edit" buttons shouldn't show up.
And we are left with:
```
A logged in user with unconfirmed e-mail sees on GUI a permanent, eyes-catching information that s/he should confirm his/her e-mail.
```
```
When logged in user with unconfirmed e-mail clicks on "Request Access" to file button, s/he sees a modal window informing that e-mail confirmation is required to perform this operation.
```
In point below -  it probably can't be done in easy way or at all. We would have to be able to resolve message from `PermissionException`
```
For API operations requiring token, we may consider changing generic message to include information about e-mail confirmation requirement.
```

Some more places that we should check to confirm if everything is in order:
 - manage permission pages should work as before (no filtering of permissions in tables for non verified users). It should work `out of the box` - but we could werify just to be sure.
 - api endpoint - `Dataverses @Path("{identifier}/contents")` - if we checked correctness of `whichChildrenHasPermissionsFor` then it should be ok.
 - api endpoint - ~`Dataverses @Path("{identifier}/roles")`~ `Dataverses @Path("{identifier}/assignments")` and `Datasets @Path("{identifier}/assignments")` - probably it would be ok as is (the main "inconsistency" here is that we don't filter out assigned roles - we just check db state), but it shouldn't matter as we need ManageDataversePermission to execute this endpoint
 - to check with @wfenrich if superuser omits rule with email verification 
 - In tast desription I can't see what we should do with Add dataverse / dataset buttons. In case repository is open (unlogged user will see this buttons and will have modals informing that he should register/log in but logged/non-verified user will not see this button at all)
