### ISSUE TITLE
Tags cannot be added to selected files

### ISSUE THREAD

**Issue by ghost** [CeON/fairchive#1648]
1. User is on files list on dataset
2. Selects 2-3 files
3. Edits and adds tag 
4. Confirmation message occurs :
 Success! – The tag(s) were successfully added for Selected Files.
 Success! – The selected files have been updated.
5. No changes applied - there i no tag on selected files

**Comment by wfenrich** [comment]
Reproducible only if it is the first operation on files. Works if it is the second. May be related to #1662?
