### ISSUE TITLE
Empty e-mail on revoke permission from dataset

### ISSUE THREAD

**Issue by ghost** [CeON/fairchive#1657]
PL

(e-mail title)[dv name]: Odebranie roli

Możesz zwrócić się do nas o pomoc pisząc na adres [e-mail]

Dziękujemy,
[dataverse name] Pomoc

EN
(e-mail title) [DV name]: Your role has been revoked

You may contact us for support at [e-mail]

Thank you,
[dataverse name] Support

**Comment by ghost** [comment]
Dupplicted https://github.com/CeON/dataverse/issues/1654

**Comment by wfenrich** [comment]
Confirmed.
