### ISSUE TITLE
Badges for other terms of use

### ISSUE THREAD

**Issue by ghost** [CeON/fairchive#1659]
On dataset
![image](https://user-images.githubusercontent.com/26048925/119645226-19700480-be1e-11eb-8e8e-b13db94c7ad8.png)

from admin dashboard >licenses
![image](https://user-images.githubusercontent.com/26048925/119645530-67850800-be1e-11eb-9245-e23ea445acc1.png)

**Comment by ghost** [comment]
Add licenses should be placed next to label not under
![image](https://user-images.githubusercontent.com/26048925/119689414-1dfde280-be49-11eb-8ebd-a3c24b66c251.png)

**Comment by wfenrich** [comment]
True and true. Moreover, the badges are also not shown on the file page. So: 

1. These badges should be visible on file page. 
2. These badges should be visible on dataset page (if there is consistency in the whole dataset). 
3. On dataset page, the badge should be placed next to the licence name, not under.
