### ISSUE TITLE
Licenses cannot be changed for the first try change

### ISSUE THREAD

**Issue by ghost** [CeON/fairchive#1662]
1. Select all files
2. Edit files 
3. Change license
4. Success message is displayed
4. No changes applied
5. Change license 2nd time
6. Changes applied

**Comment by wfenrich** [comment]
Confirmed. Nasty one, it's easy to overlook that something is wrong.

**Comment by dbojanek** [comment]
Probably same bug as in #1648

**Comment by dbojanek** [comment]
Looks like it works for DRAFTs just fine. Issue occurs when creating a DRAFT version by editing licenses on published version.
