### ISSUE TITLE
Thumbnail preview is sometimes blocked 

### ISSUE THREAD

**Issue by ghost** [CeON/fairchive#1663]
Sometimes after preview thumbnail one after one (eg when check for edit)- some of them freeze and cannot be closed

Refresh page helps
![image](https://user-images.githubusercontent.com/26048925/119666264-85119c00-be35-11eb-9602-ceba8d745906.png)

**Comment by wfenrich** [comment]
Can be seen here: testrepodurl/dataset.xhtml?persistentId=doi%3A10.18150%2FFK2%2FW41GGY&version=DRAFT

**Comment by wfenrich** [comment]
The previews start to cascade. Usually refreshing is not necessary, "mouse over" and then "mouse out" is sufficient.
