### ISSUE TITLE
In search results, old name of containing dataverse stays, although it has been changed

### ISSUE THREAD

**Issue by ghost** [CeON/fairchive#1664]
1. Dataverse B is in Dataverse A
2. Dataverse A has name changed to A1
3. On dataverse list, tile with dataverse B has still old name of containing dataverse (namely A).
4. The containing dataverse changes after edititing dataverse B data. 

![image](https://user-images.githubusercontent.com/26048925/119688915-b5af0100-be48-11eb-97c4-f05493b1ac69.png)

![image](https://user-images.githubusercontent.com/26048925/119688162-070ac080-be48-11eb-8210-d6d1a554d6f3.png)

**Comment by wfenrich** [comment]
Confirmed. Something is not reindexing after this operation?
