### ISSUE TITLE
In RDS citation, year by the publisher should be taken from somewhere else

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1702]
* for the year that stands by the publisher, we should not take the year from the publication date of a given version, but of the dataset (identically as it is on RepOD).
* for the first draft, when there is no dataset publication date, we should temporarily take the year from the last update time (identically as it is on RepOD).

**Comment by madryk** [comment]
done in: https://github.com/CeON/rds-extension/pull/20
