### ISSUE TITLE
Fix Sechema.org JSON-LD incongruencies

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1780]
* If all files have the same license: 

license: {
   @type: "CreativeWork",
   name: "[Universal license name]"
   url: "[license url]"

* If all files are restriced: 

license: {
   @type: "CreativeWork",
   name: "Restricted access"

* If all files are on "All rights reserved"

license: {
   @type: "CreativeWork",
   name: "All rights reserved"

* If there are different licenses or terms: 

license: {
   @type: "CreativeWork",
   name: "Different licenses or terms for individual files"

**Comment by madryk** [comment]
In chrome there is a plugin to validate json-ld using google validator:
https://chrome.google.com/webstore/detail/structured-data-testing-t/kfdjeigpgagildmolfanniafmplnplpl
There is also a possibility to validate directly in google:
https://search.google.com/test/rich-results?utm_campaign=sdtt&utm_medium=url

**Comment by madryk** [comment]
There is also a documentation in:
https://developers.google.com/search/docs/data-types/dataset#guidelines

**Comment by wfenrich** [comment]
For files, we should have "encodingFormat" instead of "fileFormat".
