### ISSUE TITLE
Change content of password reset and password reset confirmation emails

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1791]
Password reset: 
Skontaktuj się z nami, jeśli nie prosiłeś o reset hasła lub potrzebujesz dodatkowej pomocy.

Password reset confirmation: 
Skontaktuj się z nami, jeśli nie prosiłeś o reset hasła lub potrzebujesz dodatkowej pomocy.

These sentences are totally obsolete and we can safely remove them.

**Comment by wfenrich** [comment]
Remove also their English counterparts.

**Comment by wtr-icm** [comment]
From what I see these sentences were removed in #1723.

**Comment by wfenrich** [comment]
True. My bad.
