### ISSUE TITLE
A user signing up with shibboleth should be able to add some account information

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1796]
Currently it looks like this: 

![Firefox_Screenshot_2021-07-15T06-01-29 487Z](https://user-images.githubusercontent.com/8678301/125759883-2cd268a7-c66d-4af1-bc66-caa3b52e135a.png)

**Comment by wfenrich** [comment]
User should be able to add information regarding: 
 
* Affiliation (only if we don't take it already from IdP)
* Position
* Language

S/he should also see and accept/decline consents.

**Comment by madryk** [comment]
Right now we don't use Shibboleth for our institutional login. We have integrated https://github.com/SAML-Toolkits/java-saml for this purpose.
