### ISSUE TITLE
On dataset page, license badge should go next to the license name, not under

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1827]
![image](https://user-images.githubusercontent.com/8678301/126562134-1da67a38-d0b7-40cb-80cc-7843720e7683.png)

**Comment by wfenrich** [comment]
That's more like it: 

![image](https://user-images.githubusercontent.com/8678301/126562316-56ae463a-40b9-484c-a667-298cb4012f15.png)

**Comment by wfenrich** [comment]
Waiting for Marcin.

**Comment by sudmar** [comment]
@wfenrich it seems to work for me:

![image](https://user-images.githubusercontent.com/9151566/133731904-3096d772-7e60-428b-b535-f6944848ebd8.png)

Do you have a link to a sample dataset with this issue?

**Comment by wfenrich** [comment]
Well, currently it works for me as well. Yet another RepOD miracle! ;-)

**Comment by sudmar** [comment]
After some thought I suppose you just have had the WCAG 80 characters limit turned on. The text just barely fits, the image does not and overflows.

**Comment by wfenrich** [comment]
I guess the puzzle is solved and we can close the issue.
