### ISSUE TITLE
Fix bug occuring when trying to remove a harvesting client

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1859]

**Comment by dbojanek** [comment]
```2021-08-03T16:22:00.069+0000|Warning: EJB5123:Rolling back timed out transaction [JavaEETransactionImpl: txId=9869 nonXAResource=250 jtsTx=null localTxStatus=1 syncs=[com.sun.ejb.containers.SimpleEjbResourceHandlerImpl@bafa4e1, com.sun.ejb.containers.ContainerSynchronization@2e9c3722, org.eclipse.persistence.internal.jpa.transaction.JTATransactionWrapper$1@2cad0999, org.eclipse.persistence.transaction.JTASynchronizationListener@32ad4755, org.eclipse.persistence.internal.jpa.transaction.JTATransactionWrapper$1@44d3654d, org.eclipse.persistence.transaction.JTASynchronizationListener@bb97fd2, com.sun.enterprise.resource.pool.PoolManagerImpl$SynchronizationListener@4f9c4efd]] for [HarvestingClientsService]```
