### ISSUE TITLE
Remove some temporary files after they are not needed

### ISSUE THREAD

**Issue by madryk** [CeON/fairchive#1879]
We have some cases when we create temporary file but never remove them after the work is done.
Such files are in form:
```

tempSubsetFile2465843405109863067.tmp
tempLocalFile8286233180649395020.tmp
tempFileToRescale4901057174882206113.tmp
firstpass-2430429116362840534.tab
firstpass-2578408473252052700.csv
data-5170417214209956484.tab
d036468f-8051-406d-82bf-1928218066b82512574650660504461305af31c-5cd9-4e12-9a85-4071b9ec6e7d
tempTabfile.1257543624808568799.tab
dataverseDataFrame_867704.RData

```
We need to find code responsible for creating those and remove them after some processing is done.

**Comment by dbojanek** [comment]
- [x] tempSubsetFile2465843405109863067.tmp
- [x] tempLocalFile8286233180649395020.tmp
- [x] tempFileToRescale4901057174882206113.tmp
- [x] firstpass-2430429116362840534.tab
- [x] firstpass-2578408473252052700.csv
- [x] data-5170417214209956484.tab
- [x] d036468f-8051-406d-82bf-1928218066b82512574650660504461305af31c-5cd9-4e12-9a85-4071b9ec6e7d
- [x] tempTabfile.1257543624808568799.tab
- [x] dataverseDataFrame_867704.RData
