### ISSUE TITLE
Make OpenAIRE exporter consistent with OpenAIRE Guidelines v.2

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1948]
The v.2 Guidelines can be found here: https://guidelines.openaire.eu/en/latest/data/index.html

We should remove elements inconsistent with the schema v3.1:

1. 

Remove

```
<givenName></givenName>
<familyName></familyName>
```

from `<creator>` and `<contributor>`. 

2. 

Remove

`<fundingReferences></fundingReferences>`

and all its subelements. 

3. 

Remove attribute

`nameType=`

from` <creatorName> `and `<contributorName>`

4. 

Fix geoLocationBox

**Comment by wfenrich** [comment]
Cvc-type.3.1.1: Element 'creatorName' Is A Simple Type, So It Cannot Have Attributes, Excepting Those Whose Namespace Name Is Identical To 'http://www.w3.org/2001/XMLSchema-instance' And Whose [local Name] Is One Of 'type', 'nil', 'schemaLocation' Or 'noNamespaceSchemaLocation'. However, The Attribute, 'nameType' Was Found., Line '1', Column '339'.
    Cvc-complex-type.2.4.a: Invalid Content Was Found Starting With Element 'givenName'. One Of '{"http://datacite.org/schema/kernel-3":nameIdentifier, "http://datacite.org/schema/kernel-3":affiliation}' Is Expected., Line '1', Column '388'.
    Cvc-type.3.1.1: Element 'creatorName' Is A Simple Type, So It Cannot Have Attributes, Excepting Those Whose Namespace Name Is Identical To 'http://www.w3.org/2001/XMLSchema-instance' And Whose [local Name] Is One Of 'type', 'nil', 'schemaLocation' Or 'noNamespaceSchemaLocation'. However, The Attribute, 'nameType' Was Found., Line '1', Column '611'.
    Cvc-complex-type.2.4.a: Invalid Content Was Found Starting With Element 'givenName'. One Of '{"http://datacite.org/schema/kernel-3":nameIdentifier, "http://datacite.org/schema/kernel-3":affiliation}' Is Expected., Line '1', Column '652'.
    Cvc-type.3.1.1: Element 'contributorName' Is A Simple Type, So It Cannot Have Attributes, Excepting Those Whose Namespace Name Is Identical To 'http://www.w3.org/2001/XMLSchema-instance' And Whose [local Name] Is One Of 'type', 'nil', 'schemaLocation' Or 'noNamespaceSchemaLocation'. However, The Attribute, 'nameType' Was Found., Line '1', Column '1542'.
    Cvc-complex-type.2.4.a: Invalid Content Was Found Starting With Element 'givenName'. One Of '{"http://datacite.org/schema/kernel-3":nameIdentifier, "http://datacite.org/schema/kernel-3":affiliation}' Is Expected., Line '1', Column '1595'.
    Cvc-type.3.1.1: Element 'contributorName' Is A Simple Type, So It Cannot Have Attributes, Excepting Those Whose Namespace Name Is Identical To 'http://www.w3.org/2001/XMLSchema-instance' And Whose [local Name] Is One Of 'type', 'nil', 'schemaLocation' Or 'noNamespaceSchemaLocation'. However, The Attribute, 'nameType' Was Found., Line '1', Column '1796'.
    Cvc-type.3.1.1: Element 'contributorName' Is A Simple Type, So It Cannot Have Attributes, Excepting Those Whose Namespace Name Is Identical To 'http://www.w3.org/2001/XMLSchema-instance' And Whose [local Name] Is One Of 'type', 'nil', 'schemaLocation' Or 'noNamespaceSchemaLocation'. However, The Attribute, 'nameType' Was Found., Line '1', Column '1956'.
    Cvc-type.3.1.1: Element 'contributorName' Is A Simple Type, So It Cannot Have Attributes, Excepting Those Whose Namespace Name Is Identical To 'http://www.w3.org/2001/XMLSchema-instance' And Whose [local Name] Is One Of 'type', 'nil', 'schemaLocation' Or 'noNamespaceSchemaLocation'. However, The Attribute, 'nameType' Was Found., Line '1', Column '2124'.
    Cvc-type.3.1.1: Element 'contributorName' Is A Simple Type, So It Cannot Have Attributes, Excepting Those Whose Namespace Name Is Identical To 'http://www.w3.org/2001/XMLSchema-instance' And Whose [local Name] Is One Of 'type', 'nil', 'schemaLocation' Or 'noNamespaceSchemaLocation'. However, The Attribute, 'nameType' Was Found., Line '1', Column '2756'.
    Cvc-type.3.1.1: Element 'contributorName' Is A Simple Type, So It Cannot Have Attributes, Excepting Those Whose Namespace Name Is Identical To 'http://www.w3.org/2001/XMLSchema-instance' And Whose [local Name] Is One Of 'type', 'nil', 'schemaLocation' Or 'noNamespaceSchemaLocation'. However, The Attribute, 'nameType' Was Found., Line '1', Column '2937'.
    Cvc-complex-type.2.4.d: Invalid Content Was Found Starting With Element 'geoLocationBox'. No Child Element Is Expected At This Point., Line '1', Column '5243'.
    Cvc-type.3.1.2: Element 'geoLocationBox' Is A Simple Type, So It Must Have No Element Information Item [children]., Line '1', Column '5433'.
    Cvc-minLength-valid: Value '' With Length = '0' Is Not Facet-valid With Respect To MinLength '4' For Type 'box'., Line '1', Column '5433'.
    Cvc-type.3.1.3: The Value '' Of Element 'geoLocationBox' Is Not Valid., Line '1', Column '5433'.
    Cvc-complex-type.2.4.d: Invalid Content Was Found Starting With Element 'geoLocationBox'. No Child Element Is Expected At This Point., Line '1', Column '5527'.
    Cvc-type.3.1.2: Element 'geoLocationBox' Is A Simple Type, So It Must Have No Element Information Item [children]., Line '1', Column '5716'.
    Cvc-minLength-valid: Value '' With Length = '0' Is Not Facet-valid With Respect To MinLength '4' For Type 'box'., Line '1', Column '5716'.
    Cvc-type.3.1.3: The Value '' Of Element 'geoLocationBox' Is Not Valid., Line '1', Column '5716'.
    Cvc-complex-type.2.4.a: Invalid Content Was Found Starting With Element 'fundingReferences'. One Of '{"http://datacite.org/schema/kernel-3":language}' Is Expected., Line '1', Column '5764'.

**Comment by dbojanek** [comment]
4.0

- [x] Changing resourceTypeGeneral from optional to mandatory
- [x] Addition of a new property: FundingReference, with subproperties funderName, funderIdentifier, awardNumber, awardURI and awardTitle. Deprecation of contributorType “funder”
- [x] Addition of new optional subproperties for creatorName and contributorName: familyName and givenName
- [x] Addition of a new relatedIdentifierType option “IGSN”
- [x] Addition of a new subproperty for GeoLocation “geoLocationPolygon”, and changing the definition of the existing GeoLocation subproperties (geoLocationPoint and geoLocationBox)

4.1 

- [x] Allowing multiple polygons per GeoLocation
- [x] Addition of new optional “inPolygonPoint” subproperties for polygon
- [x] Addition of new dateType “Other”
- [x] Addition of a new resourceType “DataPaper”
- [x] Addition of three new relationType pairs: IsDescribedBy and Describes, HasVersion and IsVersionOf, IsRequiredBy and Requires
- [x] Addition of new subproperty for Date: dateInformation
- [x] Addition of a new optional attribute for creatorName and ContributorName: nameType. Controlled list: personal, organizational
- [x] Addition of a new optional “resourceTypeGeneral” attribute for relatedIdentifier. Controlled list is identical to existing resourceTypeGeneral attribute
- [x] Addition of optional lang attribute to Rights property
