### ISSUE TITLE
Fix "Assign roles" modal on phone browsers

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#2002]
![Screenshot_20210923-095644](https://user-images.githubusercontent.com/8678301/134479680-8fc51fe4-3034-4c62-b07d-03234a20ac83.jpg)
![Screenshot_20210923-095711](https://user-images.githubusercontent.com/8678301/134479855-a9270967-6de6-4a54-9898-09a11ede9220.jpg)

**Comment by wfenrich** [comment]
* A "hr" is visible over the text. 
* No radios for role selection.

**Comment by wfenrich** [comment]
#2008 May be related.

**Comment by sudmar** [comment]
@wfenrich can't reproduce either of these bugs so far.

Test phone: Moto G6 Plus @ Android 9

Chrome 93.0.4577.82:
![Screenshot_20211026-082510](https://user-images.githubusercontent.com/9151566/138820742-e7b63ca3-651c-423d-9d79-f1767014cd54.jpg)

Firefox 92.1.1:
![Screenshot_20211026-082133](https://user-images.githubusercontent.com/9151566/138820795-f6127319-f927-451f-bf31-d27b41ee6b19.jpg)

Radios are correctly rendered and the erroneous horizontal line is not present. I did those test on my local dataverse instance, so chances are whatever was causing this bug could be already fixed, or it pops up intermittently, or there might be other factors involved.

**Comment by madryk** [comment]
Could not reproduce
