### ISSUE TITLE
hr should separate only some, but not all multiplicable metadata fields

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#2042]
Currently `<hr>` separates all multiplicable fields, but in fact it is needed only for some of them. Short, unambiguous fields (like "Author" or "Keyword") do not need it and – moreover – they do not look good with it.

In the first step we should explore if we can separate only multiplicable: 
* simple textarea fields, 
* compound fields having a textarea field as one of its subfields.

**Comment by sudmar** [comment]
Seems like this can't be handled automatically; some sort of manual designation should be in place, to indicate which fields should be separated.

As of now, the line separator is added for all fields via this style in `theme-base.scss`: 

```
.datasetfield-value + .datasetfield-value {
	border-top: 1px solid $gray-border-color;
	padding-top: 8px;
```

I _think_ that the dataset metadata fields are rendered using `viewMetadataField.xhtml`. I wonder if it'd be possible to add an extra class to this element: 

```<div style="#{fieldsLoop.last ? '': 'padding-bottom: 10px;'}" class="datasetfield-value">```

For example, for fields that should be separated by a line, add class `datasetfield-separatable`, and then modify the CSS styles accordingly:

```
.datasetfield-value.datasetfield-separatable + .datasetfield-value.datasetfield-separatable {
	border-top: 1px solid $gray-border-color;
	padding-top: 8px;
```

These are just my thought, whether it's a sensible approach I don't know.
