### ISSUE TITLE
Fix Internal Server Error upon downloading ingested tabular data in RData format

### ISSUE THREAD

**Issue by tlewand42** [CeON/fairchive#2249]
It is currently impossible to download ingested tabular data in RData format.
Upon downloading from regular dataset view, user is left with no information on what happened (or is informed about "network failure").
Upon downloading from Dataverse Data Explorer ("Explore" view for ingested files), response with unspecified Internal Server Error is formed:

`{"status":"ERROR","message":"Internal server error. More details available at the server logs.","code":500,"incidentId":[guid-like-random-id]}`

**Comment by wfenrich** [comment]
On production everything is fine.
