### ISSUE TITLE
Fix message about the exceeding of max number of uploaded files in a ZIP

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#2266]
First thing is that the value of the limit is currently taken from the moon. The second thing is that the message itself is not well formed. 

EN: The number of files in the ZIP archive exceeds the limit of [limit value]. The archive will not be extracted and will be uploaded in its original ZIP format. If you want to add individual files to the dataset, please upload a ZIP archive with fewer files. 

PL: Liczba plików w archiwum ZIP przekracza limit wynoszący [limit value]. Archiwum nie zostanie rozpakowane i zostanie dodane do zbioru danych pod postacią oryginalnego pliku ZIP. Jeśli chcesz dodać do zbioru danych pojedyncze pliki, prześlij archiwum ZIP zawierające ich mniejszą liczbę.

**Comment by tlewand42** [comment]
![image](https://user-images.githubusercontent.com/108460311/207840340-6ee9a0fa-c67c-448c-9e61-31d0b1cd5595.png)

**Comment by tlewand42** [comment]
seems ok now
![image](https://user-images.githubusercontent.com/108460311/209303344-4063dcda-5608-4f9c-91b8-eb96198083db.png)

![image](https://user-images.githubusercontent.com/108460311/209303708-110c7cb0-6f29-47a5-80ff-1c46c1e64e10.png)
