### ISSUE TITLE
Some positions on "Select dataverse" are marked as expandable (they have this little triangular arrow), but their expansion reveals nothing

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#2277]
For instance "Avonlea" (view of a Superuser)

![image](https://user-images.githubusercontent.com/8678301/208876478-ad40d729-b852-4d9c-b78c-e683cd841b15.png)

"Avonlea" has one unpublished and two linked dataverses.

**Comment by tlewand42** [comment]
current hypothesis: collections containing linked collections and only linked collections are rendered as expandable. Expanding reveals true state of affairs, i.e. no collections inside.
No exceptions are thrown upon clicking such collection.
