### ISSUE TITLE
Remove nasty typo from DataCite Metadata Exporter

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#2392]
Is: 
nameIdentifierScheme="ORICD"

Should be: 
nameIdentifierScheme="ORCID"

This typo is propagated into Datacite and crashes metadata imports into OmegaPSIR.

**Comment by madryk** [comment]
Could you please elaborate? I can't see a difference between `Is:` and `Should be:`. Is it some kind of weird character problem?

**Comment by madryk** [comment]
Nevermind: `ORICD` shoud be `ORCID`
