### ISSUE TITLE
"Add dataset" button in the top menu should be visible for users that are not logged in

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#2451]
Currently it is not visible for a user that is not logged in, but we can try to place him/her in a proper workflow straight away. 

1. User is not logged in. 
2. User sees the "Add dataset" button
3. User clicks the "Add dataset" button
4. A modal windows pops up. The window contains "Close" button and a text message: 

EN: You need to <a href="https://repod.icm.edu.pl/loginpage.xhtml?redirectPage=%2Fdataverse.xhtml">Sign In/Sign Up</a> to create add a dataset.
PL: Aby  dodać zbiór danych, musisz się <a href="https://repod.icm.edu.pl/loginpage.xhtml?redirectPage=%2Fdataverse.xhtml">zalogować/zarejestrować</a>.

5a. If a user clicks "Close", the windows simply closes. Return 0; 
5b. If a user clicks the link, s/he moves to the Sign In/Sign Up page. 

6. After successful signing in, the user goes back to the page s/he was on in 4. and standard modal window for adding dataset pops up.

**Comment by diasf** [comment]
Apart from being authenticated, the display of the `Add dataset` button is also conditioned on whether the user has a confirmed e-mail. Given that, it could happen that the button disappears once the user registers/logs in, if he didn't yet confirm his mail.

**Comment by wfenrich** [comment]
@diasf Is it a hardcoded condition, or maybe it depends on whether we have an e-mail confirmation requirement active in a given installation?

**Comment by diasf** [comment]
It's based on whether we have e-mail confirmation enabled. Also if it's enabled we do show the following banner at the top:

![image](https://github.com/CeON/dataverse/assets/2997863/603ae10e-4107-4ef9-851e-aafa797f3cf3)

**Comment by wfenrich** [comment]
Then it seems OK – the requirement is not exaggerated and a user is informed why the button (and some other elements) is missing.
