### ISSUE TITLE
It should be possible to add a custom text message on the top of the "Add dataset" modal window

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#2456]
It should work similarly to the custom text message that we've made here: https://github.com/CeON/dataverse/issues/2381

The direct need results from the fact, that in RepOD some users are confused and do not know what they should do if there is no institutional collection they can fit into. They should select the root dataverse, but currently they are not informed about that. 

A the same time, in RDS it is not possible to add anything to the root dataverse – users are forced to choose one of the subdataverses. 

Thus, the messeage must be configurable per repository.

**Comment by diasf** [comment]
Similar to the sign-in use-case, the message can be modified with `SelectDataverseInfo` property (with language suffix).
