### ISSUE TITLE
explore why ingesting libreOffice-made .xslx files always end in failure

### ISSUE THREAD

**Issue by tlewand42** [CeON/fairchive#2460]
Ingest of .xslx files prepared with LibreOffice software seem to always end in failure with cryptic `no rows of data found in the Excel (XLSX) file` error description. There's even no `Ingest in progress` state visible after the file upload - the process ends with failure straight away.

The same file, even if only opened in Microsoft Excel ®️ ™️ software and then saved again, undergoes normal ingest process, with `Ingest in progress` state visible directly after the file upload and may even end with success if no other errors (than not being made by Excel, seemingly) are present.

Libre Office and Excel version of the same file differ in size and when unzipped, small differences are visible, but it is not clear, which differences exactly cause the failure. In principle, both file versions should be treated in the same manner - Libre Office, at least, thinks it's the same file format.

Version of Libre Office used: 6.4.2.2 (x64), compile id 4e471d8c02c9c90f512f7f9ead8875b57fcb1ec3

**Comment by tlewand42** [comment]
[update] .xslx file prepared with LibreOffice 7.3.7.2. has the same instant ingest fail

**Comment by tlewand42** [comment]
[update] .xslx file prepared with LibreOffice 24.2.2.2. compile d56cc158d8a96260b836f100ef4b4ef25d6f1a01 hat the same instant ingest fail.

Files were tested with both ways of obtaining .xlsx file format from Libre Office Calc, i.e. both via "Open Office XML" and "Excel 2007-365" options

**Comment by diasf** [comment]
Handled issues in PR #2472:

* Reader was fetching sheet with hard-coded id (rId1). However the id of a sheet is configurable and can be set as desired by applications creating the xslx. In this case excel starts sheet ids with rId1, rId2, ... whereas libre starts at rId2. The fix uses `getSheetData` to just fetch the first sheet.
* Excel includes a `spans` attribute for each row indicating how many columns it contains. This was used to allocate an array for the column names. Unfortunately, libre office doesn't include this attribute. The fix replaces the array with a `TreeMap` allowing to collect the column names as we parse them.

As mentioned in the PR, qe should add some various test files for common spreadsheet apps to validate that the code is behaving as expected.
