### ISSUE TITLE
Enable mass notification deletion with GUI

### ISSUE THREAD

**Issue by tlewand42** [CeON/fairchive#2509]
We need some additional elements on `Notifications` tab in user dashboard. The goal is to enable users to delete multiple notifications at once rather than deleting them one by one (which can be dramatically time-consuming after a prolonged period of suboptimal notification hygiene).

* Lazy Option: add simple `Delete all Notifications` button somewhere in the uppish regions of the dashboard. Upon clicking all notifications are deleted and the tab is cleared.
* Greedy Option: add checkboxes to all Notifications and two buttons: `Delete Notifications` and `Mark all Notifications`. "Delete Notifications" deletes all marked notofications (and produces an appropriate message if no notofication is marked). "Mark all Notifications" marks all Notifications (checks all the checkboxes).

**Comment by wfenrich** [comment]
Ad. Lazy Option: we should have an intermediary confirmation (possibly a modal window), just to avoid mass destruction caused by an accidental click. 

Ad. Greedy Option: if deletion is the only available action, it does not improve things much. If user selects only some (but not all) notifications, the only difference is that s/he has to click a checkbox instead of an "X" on the right side (the one that we have now).    We should add an intermediary confirmation for this solution as well.

**Comment by tlewand42** [comment]
one majr difference between mass checking and mass deleting is that checking in a checkbox does not trigger page reload (and the deletion does). Page trying to reload upon every deletion generates most of the lag, especially when there are many notification present on the page and the page load time is very long to begin with. Nevertheless, the rest of the argumentation is valid and proper.

**Comment by wfenrich** [comment]
We go with: 

* Pagination. It should resemble the one that we have on "Users" page. 
* Notification should be visible within a table. Columns of the table should be: Checkbox | Notification | Date and time
* Search box. For now searching by dataverse and dataset name should be enough. May resemble the simple search box that we have on "Files" tab, nothing fancy. 
* "Delete selected" button. Deletion should be confirmed on modal window, to avoid accidental erasures.
* * Deletion should include the mechanism that we have on "Files" tab that allows to select only items visible on the current page or all pages in a dataset.
