### ISSUE TITLE
Add maven release configuration/scripts

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#2548]

**Comment by diasf** [comment]
Proposed releasing scheme
----------------------------------------

From the `develop` branch we release either `minor` or `major` versions. When a release is performed a tag is created with the specific version (eg. v1.0.0, v1.2.0, v...). Versions on develop will therefor follow the pattern:

`1.0.0` -> `1.1.0` -> `1.2.0` -> `2.0.0` -> `2.1.0` -> `2.2.0` -> `2.3.0` -> ...

Should a specific version require a hotfix, we create a release branch from the tag and set the development version with the patch:

```
$ git checkout -b releases/v1.2.0 tags/v1.2.0
$ ./mvnw versions:set -DnewVersion=1.2.1-SNAPSHOT versions:commit
$ git add .
$ git commit -m 'Hotfix development version'
```

On the release branch we can then perform required hotfixes and do patch releases when necessary (eg 1.2.1, 1.2.2, ...)

If appropriate, hotfixes can then also be ported back to the main `develop` branch and other release branches.
