### ISSUE TITLE
Fix display bugs on manage groups page

### ISSUE THREAD

**Issue by madryk** [CeON/fairchive#442]

**Comment by sudmar** [comment]
@madryk didn't you mean "manage groups" page? I was going through my notes from the weekly and I don't see anything regarding the guestbook page. There doesn't seem to be anything wrong with it, though I might be mistaken.

I do however have noted a few things to fix up on the "manage groups" page (too large error messages, misstyled "cancel" buttons, etc.), so maybe that was what you meant instead? I can't remember, just asking to be sure.
