### ISSUE TITLE
Change the way of editing custom questions in guestbooks

### ISSUE THREAD

**Issue by madryk** [CeON/fairchive#513]

**Comment by wfenrich** [comment]
![image](https://user-images.githubusercontent.com/8678301/70437419-ddab7880-1a8b-11ea-9eba-cec0fa3892de.png)

**Comment by wfenrich** [comment]
Field descriptions: 

Pytania własne              

Dodaj pytania własne, by umożliwić użytkownikom pobierającym plik przekazanie dodatkowych informacji, wykraczających poza te dotyczące konta. Pytania mogą być otwarte lub jednokrotego wyboru. Odpowiedzi mogą być wymagane lub opcjonalne.

[x] Dodaj pytania własne


Typ pytania
Pytanie otwarte
Pytanie jednokrotnego wyboru

Jeśli zostanie wybrane pytanie otwarte: 
Treść pytania *


Jeśli zostanie wybrane pytanie jednokrotnego wyboru: 
Treść pytania 
Opcje odpowiedzi (wymagane co najmniej dwie) * 


[x] Wymagaj odpowiedzi na to pytanie





EN: 

Custom Questions            

Add your own questions to have users provide more than their account information when they download a file. Questions can be text or single choice. Answering questions can be required or optional.

[x] Add custom questions

Question type
Text
Single Choice


Text: 
Question Text *


Single Choice: 
Question Text *
Response Options (at least two required) *

[x] Answering this question is required
