### ISSUE TITLE
Change license information in openaire exporter

### ISSUE THREAD

**Issue by madryk** [CeON/fairchive#515]
https://guidelines.openaire.eu/en/latest/data/field_rights.html

Information about rights and licenses should consist of one element containing two subelements. Example:
Creative Commons Attribution 4.0 International

First element:

If the dataset has no files:

info:eu-repo/semantics/closedAccess

If access to at least one file in the dataset is restricted OR there is a Guestbook in the dataset:
info:eu-repo/semantics/restrictedAccess

If all files in the dataset have a license OR are "all rights reserved" AND there is no Guestbook in the dataset:

info:eu-repo/semantics/openAccess

There is also "info:eu-repo/semantics/embargoedAccess", but for now we will omit it.

Second element:

The dataset has no files:
Nothing - no second element.

All files in the dataset have the same license. Example for CC BY:

Creative Commons Attribution 4.0 International

Creative Commons Attribution 4.0 International

All files in the dataset are "all rights reserved":

All rights reserved.

Some files have one license, some files have another OR are "all rights reserved":

Different licenses and/or terms apply for individual files in the dataset.

Some files have one license, some have another or are "all rights reserved" and at least one file is restricted access.
Different licenses and/or terms apply to individual files in the dataset. Access to some files in the dataset is restricted.

Access to all files is restricted:

Access to all files in the dataset is restricted.

**Comment by wfenrich** [comment]
https://guidelines.openaire.eu/en/latest/data/field_rights.html

Information about rights and licenses should consist of one `<rightsList>` element containing two `<rights>` subelements. Example:

```
<rightsList>
<rights rightsURI=”info:eu-repo/semantics/openAccess” />
<rights rightsURI=”http://creativecommons.org/licenses/by/4.0/”>
Creative Commons Attribution 4.0 International
</rights>
</rightsList>

```

First `<rights>` element: 

If the dataset has no files: 

info:eu-repo/semantics/closedAccess

If access to at least one file in the dataset is restricted OR there is a Guestbook in the dataset:  
info:eu-repo/semantics/restrictedAccess

If all files in the dataset have a license OR are “all rights reserved” AND there is no Guestbook in the dataset: 

info:eu-repo/semantics/openAccess


There is also “info:eu-repo/semantics/embargoedAccess”, but for now we will omit it. 


Second `<rights>` element: 

The dataset has no files: 
    Nothing - no second element. 

All files in the dataset have the same license. Example for CC BY: 

`<rights rightsURI=”http://creativecommons.org/licenses/by/4.0/”>Creative Commons Attribution 4.0 International</rights>`

All files in the dataset are “all rights reserved”:

`<rights>All rights reserved.</rights>`

Some files have one license, some files have another OR are “all rights reserved”:

`<rights>Different licenses and/or terms apply for individual files in the dataset.</rights>`

Some files have one license, some have another or are “all rights reserved” and at least one file is restricted access. 

`<rights>Different licenses and/or terms apply to individual files in the dataset. Access to some files in the dataset is restricted.</rights>`

Access to all files is restricted: 

```
<rights>Access to all files in the dataset is restricted.</rights>

```
