### ISSUE TITLE
In Polish language version, In advanced search results some information is still produced in English

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#676]
![image](https://user-images.githubusercontent.com/8678301/74885028-d69ac380-5374-11ea-9686-8e8e15c66f3d.png)

![image](https://user-images.githubusercontent.com/8678301/74885326-90922f80-5375-11ea-90c9-124e27d59a42.png)

![image](https://user-images.githubusercontent.com/8678301/74885612-4bbac880-5376-11ea-8031-a19ee62709be.png)

**Comment by wfenrich** [comment]
Fixing list elements would be a bigger tast, so for now we should just fix metadata field labels ("Publication year").

**Comment by madryk** [comment]
There are also some untranslated values regarding tabular files:
Variable Label
Variable Name
