### ISSUE TITLE
Migrate Couple of Junit 4 test to Junit5 with refactoring if needed.

### ISSUE THREAD

**Issue by MrK191** [CeON/fairchive#701]
I would start with :

- IngestUtilTest
- BitSetTest
- BundleUtilTest
- DateUtilTest
- FileSizeUtilTest
- MarkupCheckerTest

Also if there are no BDD keywords (given,when,then) then they should be added in correct positions. Also all assertions should be in single "Assertions.assertAll(() -> ..., ...)". If you find any other room for improvements, they are ofc welcome.

**Comment by borkok** [comment]
Hi, just wanted to let you know I started working on this issue.

**Comment by borkok** [comment]
I have finished :-) all classes are refactored. I added BDD keywords only to tests longer than 3 LOC, migrated all tests to JUnit5 and done some refactorings where necessary.
