### ISSUE TITLE
Add list customizations for multiple response metadata lists

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#865]
* For selected fields, we would like them to sort alphabetically in selected interface language and not by the order from the TSV. (But not for all fields, so this should not be a default behavior - in MXRDR we have some lists sorted by expected popularity). 

* In RepOD and RDS, we want to be able to put some languages (Polish, English) on the top under inactive header “Popular languages” with hardcoded order, then, under inactive header “Other languages” give the rest of the languages sorted alphabetically, and at the very end add a header "Other options" with a single element - "Not applicable".

* For RDS, we would like to be able to shorten the list of available subjects, put "Social science" first,  sort the rest of the subjects alphabetically in interface language and put "Other" at the very end. (Social sciences may go with Arts and Humanities or Law, but rather not with Chemistry - it would be misleading to give such strange options in disciplinary repositories). 

* We would like to be able to group some lists by – for instance – continents, but there is no immediate need for that feature (and it seems that it is redundant with languages grouping).

**Comment by tomaszblazejczyk** [comment]
Sorting by alphabetical order can be set by input renderer option - attached example in field "subject": inserted {"sortByLocalisedStringsOrder":"true"} into datasetFieldType.inputredereroptions
