### ISSUE TITLE
A user having no dataverses, dataset or files receives a misleading information on “My data” page

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#912]
Currently it looks like this: 
![image](https://user-images.githubusercontent.com/8678301/79441775-f565b100-7fd7-11ea-923d-3e586f25e283.png)

Well, it’s not a dataverse and it’s no wonder there are no dataverses and datasets. 

Moreover, the newcomer may get scared: “Is there something wrong with my account? Should it be that way?”

Let’s change this information to a more friendly and informative: 

Here you will see your dataverses, datasets and files. Currently, you have no dataverses, datasets or files in our repository, but you can add them by clicking “Add data” button in a dataverse where you have permissions to add dataverses or datasets.

W tym miejscu zobaczysz swoje kolekcje, zbiory danych i pliki. Obecnie w naszym repozytorium nie masz żadnych kolekcji, zbiorów danych ani plików, ale możesz je dodać klikając przycisk “Dodaj dane” w kolekcji, w której posiadasz uprawnienia umożliwiające dodawanie kolekcji i zbiorów danych.

**Comment by dbojanek** [comment]
I've have used 'You have no dataverses, datasets, or files associated with your account. You can add a dataverse or dataset by clicking the Add Data button above. Read more about adding data in the...' which we had prepared for that occasion. The logic managing its display was broken
