### ISSUE TITLE
Incomplete link is passed to Twitter and Facebook

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#995]
"Wyświetl ten zbiór danych https://repod-test.icm.edu.pl/dataset.xhtml?persistentId="

**Comment by wfenrich** [comment]
Seems to be fixed.

**Comment by wfenrich** [comment]
![image](https://user-images.githubusercontent.com/8678301/118050463-9d86ae80-b37f-11eb-8de8-19210106539d.png)

**Comment by madryk** [comment]
If this concerns only datasets, then this issue was corrected as part of:  #1535

**Comment by wfenrich** [comment]
ACK, looks fine on tests.
